---
- name: install and provisioning dockers Cleanslate Servers
  hosts: all
  become: yes

  tasks:
# Docker Post Installation, enable docker without sudo
  - name: copy Application Configuration Files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: false
    loop:
      - {src: './script/cs-offsite-restore.sh', dest: './cs/cs-offsite-restore.sh'}
    become: true