---
- name: install and provisioning dockers Cleanslate Servers
  hosts: all
  become: yes

  tasks:
  - name: Upload docker-compose
    ansible.builtin.copy:
      src: ./config-template/docker-compose.yml
      dest: ./cs