---
- name: install docker containers
  hosts: all
  become: yes

  tasks:
  # split into two 
  - name: Extract mountpoint.tar.gz
    ansible.builtin.unarchive:
      src: ./mountpoint.tar.gz
      dest: "{{ ansible_env.PWD }}/cs"